"""
public_event_catalogs.py
========================
Ingestion and normalization layer for public astrophysical event catalogs.

Supported built-in catalog names
---------------------------------
``synthetic_isotropic``
    300-event synthetic isotropic dataset generated by example_event_data.py.
    Suitable for pipeline validation as an isotropic baseline.

``synthetic_preferred_axis``
    300-event synthetic dataset with a preferred-axis anomaly injected at
    strength 0.6.  Suitable for testing anomaly recovery.

``manual_ingest``
    Read a locally placed CSV or TSV file from ``data/real/``.
    See ``data/real/README_public_catalog_ingest.md`` for column-mapping details.

Real public catalog sources (manual placement required)
--------------------------------------------------------
This module does NOT download data automatically.  Real public catalogs from
sources such as NASA/IPAC, the Swift BAT3 GRB catalog, the Fermi-LAT catalog,
or the IceCube HESE event list must be downloaded by the operator and placed in
``data/real/`` before use.  See README_public_catalog_ingest.md for details.

The function ``download_or_prepare_public_catalog`` documents how to obtain
each supported catalog and returns the local file path when available.

Author: commons-sentience-sandbox
"""

from __future__ import annotations

import csv
import math
import os
import random
from typing import Any, Dict, List, Optional

# ---------------------------------------------------------------------------
# Schema constants (mirror simulation_signature_analysis.py)
# ---------------------------------------------------------------------------

SCHEMA_FIELDS = ["event_id", "energy", "arrival_time", "ra", "dec",
                 "instrument", "epoch"]

# Known real catalog identifiers and their expected CSV filename in data/real/
KNOWN_REAL_CATALOGS: Dict[str, str] = {
    # Fermi-LAT bright GRB catalog (manually obtained from HEASARC)
    "fermi_lat_grb":      "fermi_lat_grb_catalog.csv",
    # Swift BAT3 GRB catalog (manually obtained from Swift mission archive)
    "swift_bat3_grb":     "swift_bat3_grb_catalog.csv",
    # IceCube HESE event list (manually obtained from HESE public data release)
    "icecube_hese":       "icecube_hese_events.csv",
    # Generic manual-ingest placeholder
    "manual_ingest":      None,
}

# Column-name aliases: maps common source column names → schema field names
_COL_ALIASES: Dict[str, str] = {
    # event_id
    "name":        "event_id",
    "grb_name":    "event_id",
    "burst_name":  "event_id",
    "id":          "event_id",
    "event":       "event_id",
    # energy
    "fluence":     "energy",
    "t90":         "energy",      # fallback when no energy column
    "energy_gev":  "energy",
    "energy_kev":  "energy",
    "e_tev":       "energy",
    "log_e":       "energy",
    # arrival_time
    "trigger_mjd": "arrival_time",
    "mjd":         "arrival_time",
    "time":        "arrival_time",
    "trig_time":   "arrival_time",
    "t_trigger":   "arrival_time",
    "date_mjd":    "arrival_time",
    # ra
    "ra_deg":      "ra",
    "raj2000":     "ra",
    "ra_j2000":    "ra",
    # dec
    "dec_deg":     "dec",
    "dej2000":     "dec",
    "dec_j2000":   "dec",
    "de_deg":      "dec",
    # instrument
    "detector":    "instrument",
    "telescope":   "instrument",
    "mission":     "instrument",
    # epoch
    "year":        "epoch",
    "obs_date":    "epoch",
    "date":        "epoch",
    # Swift BAT-specific column names
    "bat_fluence": "energy",      # Swift BAT total fluence (erg/cm²)
    "bat_t90":     "energy",      # fallback if no fluence; duration as proxy
    "trigger_time": "arrival_time",  # Swift BAT ISO-8601 trigger timestamp
    "bat_ra":      "ra",          # BAT-refined RA (if present instead of 'ra')
    "bat_dec":     "dec",         # BAT-refined Dec
    "grb":         "event_id",    # Some Swift table exports use 'grb'
}

# ---------------------------------------------------------------------------
# Resolve data/real/ directory relative to this file's repo root
# ---------------------------------------------------------------------------

# Default null model per catalog label.  Wide-field detectors with clearly
# non-uniform sky acceptance should default to "exposure_corrected" to avoid
# confusing acceptance geometry with a real anisotropy signal.
# Any catalog not listed here defaults to "isotropic".
CATALOG_NULL_DEFAULTS: Dict[str, str] = {
    "fermi_lat_grb_catalog":   "exposure_corrected",   # Fermi GBM non-uniform SKY
    "fermi_lat_grb":           "exposure_corrected",
    "swift_bat3_grb_catalog":  "exposure_corrected",   # Swift BAT non-uniform sky
    "swift_bat3_grb":          "exposure_corrected",
    "icecube_hese_events":     "isotropic",            # IceCube: ~uniform RA coverage
    "icecube_hese":            "isotropic",
}


def default_null_mode_for_catalog(catalog_label: str) -> str:
    """Return the recommended null model for a given catalog label.

    Wide-field gamma-ray detectors (Fermi GBM, Swift BAT) have non-uniform sky
    acceptance; comparing against an isotropic null will almost always produce a
    spurious strong anomaly that is purely acceptance geometry.  These catalogs
    default to ``"exposure_corrected"``.

    Any unknown catalog defaults to ``"isotropic"`` (conservative).

    Parameters
    ----------
    catalog_label : catalog identifier string (basename of file, or short name)

    Returns
    -------
    "exposure_corrected" | "isotropic"
    """
    return CATALOG_NULL_DEFAULTS.get(catalog_label, "isotropic")


def _real_data_dir() -> str:
    """Return absolute path to the ``data/real/`` directory."""
    here = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.abspath(os.path.join(here, "..", ".."))
    return os.path.join(repo_root, "data", "real")


# ===========================================================================
# Public API
# ===========================================================================

def download_or_prepare_public_catalog(
    name: str,
    output_path: Optional[str] = None,
) -> str:
    """Prepare a public event catalog for use with this pipeline.

    For synthetic built-in catalogs, generates the dataset and writes it to
    disk if ``output_path`` is given.  For real catalogs, returns the path
    to a manually placed file in ``data/real/``.

    Parameters
    ----------
    name : catalog identifier (see module docstring for valid values)
    output_path : if provided, write the prepared catalog CSV here

    Returns
    -------
    Path to the prepared catalog CSV file.

    Notes
    -----
    This function performs NO network requests.  Real catalogs must be
    pre-downloaded and placed in ``data/real/``.  The docstring below
    describes each catalog source.

    Catalog download instructions::

        fermi_lat_grb
            Source: NASA HEASARC Fermi GRB Catalog
            URL: https://heasarc.gsfc.nasa.gov/db-perl/W3Browse/w3table.pl?tablehead=name%3Dfermilgrb
            Fields needed: name, ra_deg, dec_deg, trigger_mjd, instrument
            Export as CSV and save to: data/real/fermi_lat_grb_catalog.csv

        swift_bat3_grb
            Source: Swift BAT3 GRB Catalog (Lien et al. 2016)
            URL: https://swift.gsfc.nasa.gov/results/batgrbcat/
            Fields needed: GRBname, RA, Dec, Trigger_time_MJD
            Export as CSV and save to: data/real/swift_bat3_grb_catalog.csv

        icecube_hese
            Source: IceCube HESE public data release
            URL: https://icecube.wisc.edu/science/data/HE-nu-2010-2012
            Fields needed: event, ra, dec, energy_TeV, year
            Export as CSV and save to: data/real/icecube_hese_events.csv
    """
    if name in ("synthetic_isotropic", "synthetic_preferred_axis"):
        return _prepare_synthetic_catalog(name, output_path)

    # Real catalog: locate in data/real/
    if name in KNOWN_REAL_CATALOGS:
        fname = KNOWN_REAL_CATALOGS[name]
        if fname is None:
            raise ValueError(
                f"Catalog {name!r} requires a manually provided file path. "
                "Use load_public_catalog(path) directly."
            )
        path = os.path.join(_real_data_dir(), fname)
    else:
        # treat as direct path
        path = name

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Catalog file not found: {path}\n"
            "Real public catalogs must be downloaded manually and placed in data/real/.\n"
            "See data/real/README_public_catalog_ingest.md for instructions."
        )
    return path


def load_public_catalog(name_or_path: str) -> List[Dict[str, Any]]:
    """Load and normalize a public event catalog into the standard schema.

    Parameters
    ----------
    name_or_path : either a built-in catalog name OR a file system path to
                   a CSV/TSV file.  Column names are automatically mapped using
                   ``_COL_ALIASES``.

    Returns
    -------
    List of dicts with keys: event_id, energy, arrival_time, ra, dec,
    instrument, epoch.  Unresolvable fields are set to None.

    Source-specific notes
    ---------------------
    - Fermi-LAT: trigger_mjd → arrival_time; ra_deg → ra; dec_deg → dec
    - Swift BAT3: trigger_time_MJD → arrival_time; fluence (1-150 keV) → energy
    - IceCube HESE: energy_TeV re-labelled as energy; no standard energy unit
      conversion applied here (use energy as a relative field only)
    - Synthetic: generated by example_event_data.py, see that module for schema
    """
    # Built-in synthetic catalogs
    if name_or_path in ("synthetic_isotropic", "synthetic_preferred_axis"):
        path = _prepare_synthetic_catalog(name_or_path, output_path=None)
        raw_records = _read_csv_or_tsv(path)
        return _normalize_records(raw_records, source_name=name_or_path)

    # Otherwise treat as file path
    path = name_or_path

    # Resolve known catalog names to their file paths
    if name_or_path in KNOWN_REAL_CATALOGS:
        fname = KNOWN_REAL_CATALOGS[name_or_path]
        if fname:
            path = os.path.join(_real_data_dir(), fname)

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Catalog file not found: {path}\n"
            "Place the file in data/real/ and try again.\n"
            "See data/real/README_public_catalog_ingest.md for column-mapping details."
        )

    raw_records = _read_csv_or_tsv(path)
    source_name = os.path.splitext(os.path.basename(path))[0]
    return _normalize_records(raw_records, source_name=source_name)


def describe_catalog_coverage(events: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Summarize catalog coverage and data quality.

    Parameters
    ----------
    events : normalized event list (output of load_public_catalog)

    Returns
    -------
    Dict with keys:
      event_count, available_fields, missingness, ra_dec_coverage,
      time_span_mjd, instrument_labels
    """
    n = len(events)
    if n == 0:
        return {
            "event_count": 0,
            "available_fields": [],
            "missingness": {},
            "ra_dec_coverage": {},
            "time_span_mjd": {},
            "instrument_labels": [],
        }

    # Which SCHEMA_FIELDS are present in any record
    available = [f for f in SCHEMA_FIELDS
                 if any(e.get(f) is not None for e in events)]

    # Missingness: fraction of records where each field is None
    missingness = {}
    for f in SCHEMA_FIELDS:
        missing_count = sum(1 for e in events if e.get(f) is None)
        missingness[f] = round(missing_count / n, 4)

    # RA/Dec coverage
    ras  = [e["ra"]  for e in events if e.get("ra")  is not None]
    decs = [e["dec"] for e in events if e.get("dec") is not None]
    ra_dec_coverage: Dict[str, Any] = {}
    if ras:
        ra_dec_coverage["ra_min"]  = min(ras)
        ra_dec_coverage["ra_max"]  = max(ras)
        ra_dec_coverage["dec_min"] = min(decs) if decs else None
        ra_dec_coverage["dec_max"] = max(decs) if decs else None
        ra_dec_coverage["n_with_position"] = len(ras)
    else:
        ra_dec_coverage["n_with_position"] = 0

    # Time span
    times = [e["arrival_time"] for e in events if e.get("arrival_time") is not None]
    time_span: Dict[str, Any] = {}
    if times:
        time_span["t_min_mjd"] = min(times)
        time_span["t_max_mjd"] = max(times)
        time_span["span_days"] = max(times) - min(times)
        time_span["n_with_time"] = len(times)
    else:
        time_span["n_with_time"] = 0

    # Instrument labels
    instruments = sorted({e.get("instrument") or "unknown" for e in events})

    return {
        "event_count":       n,
        "available_fields":  available,
        "missingness":       missingness,
        "ra_dec_coverage":   ra_dec_coverage,
        "time_span_mjd":     time_span,
        "instrument_labels": instruments,
    }


# ===========================================================================
# Internal helpers
# ===========================================================================

def _prepare_synthetic_catalog(
    name: str,
    output_path: Optional[str],
) -> str:
    """Generate a synthetic catalog, write to a temp file if needed, return path."""
    from reality_audit.data_analysis.example_event_data import (
        generate_example_event_dataset,
    )

    if name == "synthetic_isotropic":
        events = generate_example_event_dataset(n=300, seed=42)
    elif name == "synthetic_preferred_axis":
        # Generate isotropic then apply preferred-axis injection
        from reality_audit.data_analysis.simulation_signature_analysis import (
            standardize_events, inject_synthetic_anomaly,
        )
        raw_events = generate_example_event_dataset(n=300, seed=42)
        std_events = standardize_events(raw_events)
        events = inject_synthetic_anomaly(
            std_events,
            anomaly_type="preferred_axis",
            strength=0.6,
            seed=0,
        )
        # Flatten to plain dicts with schema fields only
        events = [_flatten_record(e) for e in events]
    else:
        raise ValueError(f"Unknown synthetic catalog name: {name!r}")

    # If no output_path requested, write to a temp location under data/real/
    if output_path is None:
        os.makedirs(_real_data_dir(), exist_ok=True)
        output_path = os.path.join(_real_data_dir(), f"_synthetic_{name}.csv")

    _write_events_csv(events, output_path)
    return output_path


def _flatten_record(rec: Dict[str, Any]) -> Dict[str, Any]:
    """Strip internal _* fields and return clean schema-keyed dict."""
    return {f: rec.get(f) for f in SCHEMA_FIELDS}


def _read_csv_or_tsv(path: str) -> List[Dict[str, str]]:
    """Read a CSV or TSV file and return list of raw string dicts."""
    # Detect delimiter from file extension or try to sniff
    ext = os.path.splitext(path)[1].lower()
    if ext in (".tsv", ".txt"):
        delimiter = "\t"
    else:
        # Try to sniff
        with open(path, newline="") as f:
            sample = f.read(4096)
        tab_count   = sample.count("\t")
        comma_count = sample.count(",")
        delimiter = "\t" if tab_count > comma_count else ","

    records = []
    with open(path, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f, delimiter=delimiter)
        for row in reader:
            records.append(dict(row))
    return records


def _normalize_records(
    raw_records: List[Dict[str, str]],
    source_name: str = "unknown",
) -> List[Dict[str, Any]]:
    """Map raw column names to schema fields and coerce numeric types."""
    normalized = []
    for i, raw in enumerate(raw_records):
        rec: Dict[str, Any] = {f: None for f in SCHEMA_FIELDS}

        # Build a lower-case key copy for alias matching
        lc_raw = {k.strip().lower(): v for k, v in raw.items()}

        # Phase 1: direct match (case-insensitive)
        for k, v in lc_raw.items():
            if k in SCHEMA_FIELDS:
                rec[k] = v

        # Phase 2: apply column aliases
        for k, v in lc_raw.items():
            alias_target = _COL_ALIASES.get(k)
            if alias_target and rec.get(alias_target) is None:
                rec[alias_target] = v

        # Phase 3: fallback event_id
        if rec["event_id"] is None or rec["event_id"] == "":
            rec["event_id"] = f"{source_name}_{i:06d}"

        # Phase 4: coerce numerics
        for field in ("energy", "arrival_time", "ra", "dec"):
            val = rec[field]
            if val is not None and val != "":
                try:
                    rec[field] = float(val)
                except (ValueError, TypeError):
                    rec[field] = None
            else:
                rec[field] = None

        # Phase 5: fill instrument / epoch with source name if missing
        if not rec["instrument"]:
            rec["instrument"] = source_name
        if not rec["epoch"]:
            rec["epoch"] = source_name

        # Phase 6: derived galactic proxy
        if rec["dec"] is not None:
            rec["_b_proxy"] = abs(rec["dec"])

        normalized.append(rec)
    return normalized


def _write_events_csv(events: List[Dict[str, Any]], path: str) -> None:
    """Write a list of event dicts to CSV using the schema field order."""
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=SCHEMA_FIELDS, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(events)
