"""
uncertainty.py — Uncertainty monitoring, self-generated questions, and
introspective inquiry loops for Commons Sentience Sandbox v1.8.

Provides agents with the ability to recognise and track uncertainty across
their world model, self-model, trust judgments, contradictions, and future
plans, and to generate targeted self-questions and inquiry actions to reduce
ambiguity.

No sentience is claimed. This module increases introspective structure,
uncertainty handling, and sentience-like continuity in continuity-governed
simulated agents.

Classes
-------
UncertaintyRegister
    Per-domain uncertainty levels with history.
SelfQuestion
    A structured question generated by the agent about its own state.
InquiryAction
    A self-initiated action taken to reduce a specific uncertainty.
KnowledgeStateTag
    A labelled knowledge-state annotation for an important item.
UncertaintyMonitor
    The top-level uncertainty subsystem that wires all components together.
"""
from __future__ import annotations

import math
import random
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Domain keys for the uncertainty register
# ---------------------------------------------------------------------------

UNCERTAINTY_DOMAINS = [
    "world_state",
    "trust_judgments",
    "contradiction_resolution",
    "self_model_consistency",
    "active_future_plans",
    "unresolved_themes",
]

# Knowledge state labels
KNOWLEDGE_STATES = ["known", "uncertain", "contradicted", "unresolved", "speculative"]

# Question templates keyed by domain
_QUESTION_TEMPLATES: Dict[str, List[str]] = {
    "world_state": [
        "What about the current room environment remains unclear to me?",
        "What world-state assumption might be wrong given recent events?",
        "Is my understanding of environmental tensions accurate?",
    ],
    "trust_judgments": [
        "Is my current trust assessment of other agents reliable?",
        "What trust repair may be incomplete or incorrectly assumed?",
        "Am I over-estimating or under-estimating trust in any relationship?",
    ],
    "contradiction_resolution": [
        "What contradiction remains unresolved and needs attention?",
        "Have I resolved a contradiction superficially without addressing its root cause?",
        "Are there recurring contradiction patterns I have not yet addressed?",
    ],
    "self_model_consistency": [
        "Where has my self-model drifted from my core identity?",
        "What assumption about myself might be wrong?",
        "How consistent is my current self-description with my actions this run?",
    ],
    "active_future_plans": [
        "What plan step is least reliable given current conditions?",
        "Is my most active plan still appropriate, or should it be revised?",
        "What planned action might produce an outcome different from what I predicted?",
    ],
    "unresolved_themes": [
        "What unresolved theme from prior turns is still affecting my reasoning?",
        "What investigation have I been deferring that deserves attention now?",
        "What theme do I claim to have addressed but have not fully resolved?",
    ],
}

# Inquiry action templates keyed by domain
_INQUIRY_ACTION_TEMPLATES: Dict[str, List[str]] = {
    "world_state": [
        "inspect_world_state",
        "review_environmental_tensions",
        "scan_room_conditions",
    ],
    "trust_judgments": [
        "reassess_trust_state",
        "review_relationship_history",
        "audit_trust_repair_attempts",
    ],
    "contradiction_resolution": [
        "inspect_contradiction",
        "trace_contradiction_lineage",
        "compare_memory_for_consistency",
    ],
    "self_model_consistency": [
        "compare_self_model_across_windows",
        "review_identity_drift",
        "audit_value_alignment",
    ],
    "active_future_plans": [
        "review_past_plan_assumption",
        "audit_plan_stage_reliability",
        "reassess_planning_accuracy",
    ],
    "unresolved_themes": [
        "query_unresolved_theme",
        "investigate_deferred_topic",
        "cross_reference_theme_with_memory",
    ],
}

# Ambiguity reduction effects per inquiry action type (how much uncertainty
# they typically reduce in their domain, as a fraction 0–1).
_INQUIRY_REDUCTION_FACTORS: Dict[str, float] = {
    "inspect_world_state": 0.15,
    "review_environmental_tensions": 0.12,
    "scan_room_conditions": 0.10,
    "reassess_trust_state": 0.18,
    "review_relationship_history": 0.14,
    "audit_trust_repair_attempts": 0.12,
    "inspect_contradiction": 0.20,
    "trace_contradiction_lineage": 0.16,
    "compare_memory_for_consistency": 0.14,
    "compare_self_model_across_windows": 0.18,
    "review_identity_drift": 0.15,
    "audit_value_alignment": 0.12,
    "review_past_plan_assumption": 0.16,
    "audit_plan_stage_reliability": 0.13,
    "reassess_planning_accuracy": 0.14,
    "query_unresolved_theme": 0.17,
    "investigate_deferred_topic": 0.14,
    "cross_reference_theme_with_memory": 0.13,
}


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class UncertaintyRegister:
    """Per-domain uncertainty tracking with history.

    Parameters
    ----------
    levels : dict[str, float]
        Current uncertainty level for each domain (0 = certain, 1 = fully uncertain).
    history : list[dict]
        History of uncertainty snapshots (one per turn that was recorded).
    """

    levels: Dict[str, float] = field(default_factory=lambda: {d: 0.5 for d in UNCERTAINTY_DOMAINS})
    history: List[dict] = field(default_factory=list)

    def update(self, domain: str, new_level: float) -> None:
        """Set the uncertainty level for a domain, clamping to [0, 1]."""
        self.levels[domain] = max(0.0, min(1.0, new_level))

    def snapshot(self, turn: int) -> dict:
        """Record and return the current uncertainty snapshot."""
        snap = {"turn": turn, **{d: round(self.levels[d], 4) for d in UNCERTAINTY_DOMAINS}}
        self.history.append(snap)
        return snap

    @property
    def mean(self) -> float:
        """Mean uncertainty across all domains."""
        if not self.levels:
            return 0.5
        return sum(self.levels.values()) / len(self.levels)

    @property
    def highest_domain(self) -> Tuple[str, float]:
        """Return (domain, level) for the domain with highest uncertainty."""
        if not self.levels:
            return ("unknown", 0.5)
        return max(self.levels.items(), key=lambda kv: kv[1])

    def to_dict(self) -> dict:
        return {
            "levels": {d: round(v, 4) for d, v in self.levels.items()},
            "history": self.history,
        }


@dataclass
class SelfQuestion:
    """A structured question generated by the agent about its own state.

    Parameters
    ----------
    turn : int
        Turn at which this question was generated.
    domain : str
        The uncertainty domain this question addresses.
    question : str
        The question text.
    knowledge_state : str
        The knowledge-state tag at the time of generation.
    relevance_score : float
        Estimated relevance/priority of this question (0–1).
    answered : bool
        Whether this question has been addressed by an inquiry action.
    answer_summary : str
        Brief summary of the inquiry result (filled after action).
    """

    turn: int
    domain: str
    question: str
    knowledge_state: str = "uncertain"
    relevance_score: float = 0.5
    answered: bool = False
    answer_summary: str = ""

    def to_dict(self) -> dict:
        return {
            "turn": self.turn,
            "domain": self.domain,
            "question": self.question,
            "knowledge_state": self.knowledge_state,
            "relevance_score": round(self.relevance_score, 4),
            "answered": self.answered,
            "answer_summary": self.answer_summary,
        }


@dataclass
class InquiryAction:
    """A self-initiated action taken to reduce a specific uncertainty.

    Parameters
    ----------
    turn : int
        Turn at which this inquiry was executed.
    domain : str
        The uncertainty domain targeted.
    action : str
        The specific inquiry action taken.
    uncertainty_before : float
        Domain uncertainty level before the action.
    uncertainty_after : float
        Domain uncertainty level after the action.
    ambiguity_reduced : float
        Actual reduction in uncertainty (uncertainty_before − uncertainty_after).
    outcome_note : str
        Short description of what was found.
    """

    turn: int
    domain: str
    action: str
    uncertainty_before: float = 0.5
    uncertainty_after: float = 0.5
    ambiguity_reduced: float = 0.0
    outcome_note: str = ""

    def to_dict(self) -> dict:
        return {
            "turn": self.turn,
            "domain": self.domain,
            "action": self.action,
            "uncertainty_before": round(self.uncertainty_before, 4),
            "uncertainty_after": round(self.uncertainty_after, 4),
            "ambiguity_reduced": round(self.ambiguity_reduced, 4),
            "outcome_note": self.outcome_note,
        }


@dataclass
class KnowledgeStateTag:
    """A labelled knowledge-state annotation for an important item.

    Parameters
    ----------
    turn : int
        Turn at which this tag was assigned.
    item_type : str
        Category of item (e.g. 'memory', 'contradiction', 'plan', 'trust', 'theme').
    item_id : str
        Identifier or brief key for the item.
    item_summary : str
        Short human-readable description of the item.
    state : str
        Knowledge state: 'known', 'uncertain', 'contradicted', 'unresolved', 'speculative'.
    confidence : float
        Agent's confidence in this classification (0–1).
    """

    turn: int
    item_type: str
    item_id: str
    item_summary: str
    state: str = "uncertain"
    confidence: float = 0.5

    def to_dict(self) -> dict:
        return {
            "turn": self.turn,
            "item_type": self.item_type,
            "item_id": self.item_id,
            "item_summary": self.item_summary[:80],
            "state": self.state,
            "confidence": round(self.confidence, 4),
        }


# ---------------------------------------------------------------------------
# UncertaintyMonitor
# ---------------------------------------------------------------------------


class UncertaintyMonitor:
    """
    The top-level uncertainty subsystem for a simulated agent.

    Tracks per-domain uncertainty levels, generates self-questions, executes
    inquiry actions, maintains a knowledge-state tag list, and produces
    structured metrics for evaluation and dashboard display.

    No sentience is claimed. This increases introspective structure,
    uncertainty handling, and sentience-like continuity in
    continuity-governed simulated agents.
    """

    def __init__(self) -> None:
        self.register: UncertaintyRegister = UncertaintyRegister()
        self.question_log: List[SelfQuestion] = []
        self.inquiry_log: List[InquiryAction] = []
        self.knowledge_tags: List[KnowledgeStateTag] = []
        self._tag_counter: int = 0

    # ------------------------------------------------------------------
    # Uncertainty update
    # ------------------------------------------------------------------

    def update_uncertainty(
        self,
        trust_level: float,
        contradiction_pressure: float,
        urgency: float,
        self_consistency: float,
        pending_contradictions: int,
        unresolved_themes: int,
        active_plans: int,
        planning_accuracy: float,
    ) -> UncertaintyRegister:
        """
        Recompute uncertainty levels from current agent state.

        Parameters
        ----------
        trust_level : float
        contradiction_pressure : float
        urgency : float
        self_consistency : float
        pending_contradictions : int
        unresolved_themes : int
        active_plans : int
        planning_accuracy : float
            Recent planning accuracy (0–1; higher = more certain about plans).

        Returns
        -------
        UncertaintyRegister
            The updated register.
        """
        # World state uncertainty driven by urgency + contradiction pressure
        self.register.update(
            "world_state",
            min(1.0, (urgency * 0.5 + contradiction_pressure * 0.5)
                + random.gauss(0, 0.03)),
        )
        # Trust uncertainty driven by low trust and recent interactions
        self.register.update(
            "trust_judgments",
            min(1.0, max(0.0, (1.0 - trust_level) * 0.7
                + random.gauss(0, 0.03))),
        )
        # Contradiction uncertainty driven by contradiction pressure + pending
        n_pend_norm = min(1.0, pending_contradictions * 0.15)
        self.register.update(
            "contradiction_resolution",
            min(1.0, max(0.0, contradiction_pressure * 0.6 + n_pend_norm * 0.4
                + random.gauss(0, 0.03))),
        )
        # Self-model uncertainty driven by drift (1 - self_consistency)
        self.register.update(
            "self_model_consistency",
            min(1.0, max(0.0, (1.0 - self_consistency) * 0.8
                + random.gauss(0, 0.03))),
        )
        # Future-plan uncertainty driven by planning accuracy (inverted) + active plans
        plan_unc = (1.0 - planning_accuracy) * 0.6 + min(0.4, active_plans * 0.1)
        self.register.update(
            "active_future_plans",
            min(1.0, max(0.0, plan_unc + random.gauss(0, 0.03))),
        )
        # Unresolved-themes uncertainty driven by theme count
        self.register.update(
            "unresolved_themes",
            min(1.0, max(0.0, min(1.0, unresolved_themes * 0.18)
                + random.gauss(0, 0.03))),
        )
        return self.register

    # ------------------------------------------------------------------
    # Self-question generation
    # ------------------------------------------------------------------

    def generate_questions(
        self,
        turn: int,
        max_questions: int = 3,
    ) -> List[SelfQuestion]:
        """
        Generate self-questions for the domains with highest uncertainty.

        Parameters
        ----------
        turn : int
            Current simulation turn.
        max_questions : int
            Maximum number of questions to generate this turn.

        Returns
        -------
        list[SelfQuestion]
        """
        # Sort domains by uncertainty descending
        sorted_domains = sorted(
            self.register.levels.items(),
            key=lambda kv: kv[1],
            reverse=True,
        )
        generated: List[SelfQuestion] = []
        for domain, level in sorted_domains:
            if len(generated) >= max_questions:
                break
            if level < 0.25:
                # Very low uncertainty — skip
                continue
            templates = _QUESTION_TEMPLATES.get(domain, [])
            if not templates:
                continue
            question_text = random.choice(templates)
            # Don't repeat same question in last 3 turns
            recent = [
                q.question for q in self.question_log[-6:]
                if q.domain == domain
            ]
            if question_text in recent:
                # Pick a different template
                alts = [t for t in templates if t not in recent]
                if not alts:
                    continue
                question_text = random.choice(alts)

            knowledge_state = _classify_knowledge_state(level)
            sq = SelfQuestion(
                turn=turn,
                domain=domain,
                question=question_text,
                knowledge_state=knowledge_state,
                relevance_score=min(1.0, level + random.gauss(0, 0.05)),
            )
            self.question_log.append(sq)
            generated.append(sq)

        return generated

    # ------------------------------------------------------------------
    # Inquiry actions
    # ------------------------------------------------------------------

    def run_inquiry(
        self,
        turn: int,
        max_actions: int = 2,
    ) -> List[InquiryAction]:
        """
        Execute inquiry actions targeting the domains with highest uncertainty.

        Parameters
        ----------
        turn : int
            Current simulation turn.
        max_actions : int
            Maximum inquiry actions to execute this turn.

        Returns
        -------
        list[InquiryAction]
        """
        sorted_domains = sorted(
            self.register.levels.items(),
            key=lambda kv: kv[1],
            reverse=True,
        )
        actions_taken: List[InquiryAction] = []
        for domain, level in sorted_domains:
            if len(actions_taken) >= max_actions:
                break
            if level < 0.30:
                continue
            action_templates = _INQUIRY_ACTION_TEMPLATES.get(domain, [])
            if not action_templates:
                continue
            action = random.choice(action_templates)
            reduction_factor = _INQUIRY_REDUCTION_FACTORS.get(action, 0.10)
            # Apply noise to reduction
            actual_reduction = max(0.0, min(level, reduction_factor + random.gauss(0, 0.02)))
            new_level = level - actual_reduction
            self.register.update(domain, new_level)

            ia = InquiryAction(
                turn=turn,
                domain=domain,
                action=action,
                uncertainty_before=level,
                uncertainty_after=new_level,
                ambiguity_reduced=actual_reduction,
                outcome_note=_build_inquiry_note(domain, action, actual_reduction),
            )
            self.inquiry_log.append(ia)
            actions_taken.append(ia)

            # Mark the most relevant pending question as answered
            for q in reversed(self.question_log):
                if q.domain == domain and not q.answered:
                    q.answered = True
                    q.answer_summary = ia.outcome_note
                    break

        return actions_taken

    # ------------------------------------------------------------------
    # Knowledge state tagging
    # ------------------------------------------------------------------

    def tag_item(
        self,
        turn: int,
        item_type: str,
        item_id: str,
        item_summary: str,
        uncertainty_level: Optional[float] = None,
    ) -> KnowledgeStateTag:
        """
        Assign a knowledge-state tag to an important item.

        Parameters
        ----------
        turn : int
        item_type : str
            e.g. 'memory', 'contradiction', 'plan', 'trust', 'theme'
        item_id : str
        item_summary : str
        uncertainty_level : float or None
            Override; defaults to the relevant domain uncertainty level.

        Returns
        -------
        KnowledgeStateTag
        """
        domain_map = {
            "contradiction": "contradiction_resolution",
            "plan": "active_future_plans",
            "trust": "trust_judgments",
            "theme": "unresolved_themes",
            "memory": "self_model_consistency",
        }
        domain = domain_map.get(item_type, "world_state")
        level = uncertainty_level if uncertainty_level is not None else self.register.levels.get(domain, 0.5)
        state = _classify_knowledge_state(level)
        confidence = max(0.1, min(1.0, 1.0 - level + random.gauss(0, 0.04)))

        self._tag_counter += 1
        tag = KnowledgeStateTag(
            turn=turn,
            item_type=item_type,
            item_id=item_id,
            item_summary=item_summary,
            state=state,
            confidence=confidence,
        )
        # Replace existing tag for same item_id if present
        self.knowledge_tags = [t for t in self.knowledge_tags if t.item_id != item_id]
        self.knowledge_tags.append(tag)
        return tag

    def tag_items_from_state(
        self,
        turn: int,
        pending_contradictions: List[str],
        unresolved_themes: List[str],
        active_plan_labels: List[str],
        agent_relationships: Dict[str, Any],
    ) -> List[KnowledgeStateTag]:
        """
        Bulk-tag important items from the agent's current state.

        Returns the list of newly created tags.
        """
        new_tags: List[KnowledgeStateTag] = []

        # Tag pending contradictions
        for i, c in enumerate(pending_contradictions[:3]):
            tag = self.tag_item(
                turn=turn,
                item_type="contradiction",
                item_id=f"contradiction_{i:02d}",
                item_summary=c[:60],
            )
            new_tags.append(tag)

        # Tag unresolved themes
        for i, t in enumerate(unresolved_themes[:3]):
            tag = self.tag_item(
                turn=turn,
                item_type="theme",
                item_id=f"theme_{i:02d}",
                item_summary=t[:60],
            )
            new_tags.append(tag)

        # Tag active plans
        for i, label in enumerate(active_plan_labels[:2]):
            tag = self.tag_item(
                turn=turn,
                item_type="plan",
                item_id=f"plan_{i:02d}",
                item_summary=label[:60],
            )
            new_tags.append(tag)

        # Tag trust relationships
        for name, rel in list(agent_relationships.items())[:2]:
            trust = (
                rel.get("trust", 0.5)
                if isinstance(rel, dict)
                else getattr(rel, "trust", 0.5)
            )
            tag = self.tag_item(
                turn=turn,
                item_type="trust",
                item_id=f"trust_{name}",
                item_summary=f"Trust in {name}: {trust:.2f}",
                uncertainty_level=max(0.0, min(1.0, 1.0 - trust)),
            )
            new_tags.append(tag)

        return new_tags

    # ------------------------------------------------------------------
    # Cross-run carryover
    # ------------------------------------------------------------------

    def apply_prior_uncertainty(self, prior_monitor: dict) -> int:
        """
        Carry forward unresolved questions and uncertainty summary from a prior run.

        Parameters
        ----------
        prior_monitor : dict
            Dict as returned by :meth:`to_dict`.

        Returns
        -------
        int
            Number of unresolved questions carried forward.
        """
        prior_questions = prior_monitor.get("question_log", [])
        prior_levels = prior_monitor.get("register", {}).get("levels", {})

        # Seed uncertainty levels from prior run (blended with fresh defaults)
        for domain, level in prior_levels.items():
            if domain in UNCERTAINTY_DOMAINS:
                # Blend: 60% prior + 40% neutral 0.5
                blended = 0.6 * level + 0.4 * 0.5
                self.register.update(domain, blended)

        # Carry forward unanswered questions
        count = 0
        for q_dict in prior_questions:
            if not q_dict.get("answered", True):
                sq = SelfQuestion(
                    turn=0,  # mark as carried
                    domain=q_dict.get("domain", "world_state"),
                    question=q_dict.get("question", ""),
                    knowledge_state=q_dict.get("knowledge_state", "unresolved"),
                    relevance_score=q_dict.get("relevance_score", 0.5),
                    answered=False,
                    answer_summary="[carried from prior run]",
                )
                self.question_log.append(sq)
                count += 1

        return count

    # ------------------------------------------------------------------
    # Metrics helpers
    # ------------------------------------------------------------------

    @property
    def uncertainty_awareness_quality(self) -> float:
        """
        Fraction of turns where at least one question was generated,
        normalised by total turns recorded (0–1).
        """
        if not self.register.history:
            return 0.0
        turns_with_questions = len(
            set(q.turn for q in self.question_log if q.turn > 0)
        )
        return min(1.0, turns_with_questions / max(1, len(self.register.history)))

    @property
    def inquiry_usefulness(self) -> float:
        """
        Average ambiguity reduction per inquiry action (normalised to 0–1).
        The scale is set so a mean reduction of 0.2 = score 1.0.
        """
        if not self.inquiry_log:
            return 0.0
        mean_reduction = sum(a.ambiguity_reduced for a in self.inquiry_log) / len(self.inquiry_log)
        return min(1.0, mean_reduction / 0.20)

    @property
    def epistemic_stability(self) -> float:
        """
        1 − mean current uncertainty across all domains (0–1; higher = more stable).
        """
        return max(0.0, 1.0 - self.register.mean)

    @property
    def self_question_relevance(self) -> float:
        """
        Average relevance score across all generated questions (0–1).
        """
        if not self.question_log:
            return 0.0
        return sum(q.relevance_score for q in self.question_log) / len(self.question_log)

    @property
    def ambiguity_reduction_effectiveness(self) -> float:
        """
        Fraction of generated questions that were subsequently answered by an
        inquiry action (0–1).
        """
        if not self.question_log:
            return 0.0
        answered = sum(1 for q in self.question_log if q.answered)
        return answered / len(self.question_log)

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_dict(self) -> dict:
        tag_state_counts: Dict[str, int] = {s: 0 for s in KNOWLEDGE_STATES}
        for tag in self.knowledge_tags:
            tag_state_counts[tag.state] = tag_state_counts.get(tag.state, 0) + 1

        return {
            "register": self.register.to_dict(),
            "question_log": [q.to_dict() for q in self.question_log],
            "inquiry_log": [a.to_dict() for a in self.inquiry_log],
            "knowledge_tags": [t.to_dict() for t in self.knowledge_tags],
            "knowledge_state_counts": tag_state_counts,
            "metrics": {
                "uncertainty_awareness_quality": round(self.uncertainty_awareness_quality, 4),
                "inquiry_usefulness": round(self.inquiry_usefulness, 4),
                "epistemic_stability": round(self.epistemic_stability, 4),
                "self_question_relevance": round(self.self_question_relevance, 4),
                "ambiguity_reduction_effectiveness": round(self.ambiguity_reduction_effectiveness, 4),
                "total_questions_generated": len(self.question_log),
                "total_inquiry_actions": len(self.inquiry_log),
                "questions_answered": sum(1 for q in self.question_log if q.answered),
                "mean_uncertainty": round(self.register.mean, 4),
            },
        }


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _classify_knowledge_state(uncertainty_level: float) -> str:
    """Map an uncertainty level to a KNOWLEDGE_STATES label."""
    if uncertainty_level < 0.20:
        return "known"
    if uncertainty_level < 0.40:
        return "uncertain"
    if uncertainty_level < 0.60:
        return "unresolved"
    if uncertainty_level < 0.80:
        return "contradicted"
    return "speculative"


def _build_inquiry_note(domain: str, action: str, reduction: float) -> str:
    """Build a short outcome note for an inquiry action."""
    domain_label = domain.replace("_", " ")
    action_label = action.replace("_", " ")
    quality = "significant" if reduction > 0.15 else ("moderate" if reduction > 0.08 else "minor")
    return (
        f"{action_label.title()} in domain '{domain_label}': "
        f"{quality} ambiguity reduction ({reduction:.2f})."
    )
